### ISSUE TITLE
Obsolete files

### ISSUE THREAD

**Issue by yaniv14** [thirtybees/coreupdater#6]
On a compare scan I ran I've got thousands of obsolete files.
I see the mentioned note about not having a select all button which make sense.
In my case 99 % of the files are from ```admin``` folder.
and almost all of them are from ```admin_folder/autoupgrade/latest```
isn't that something that better have a checkbox? this test was on a shop migrated from PS and also had an autoupgrade back then with PS.
I think that ```thirty bees Updater``` module use the same location for upgrades.

**Comment by Traumflug** [comment]
The simple way to solve this is to remove these files by FTP or on the shell. Entire folder `autoupgrade/` can go away.

Having checkboxes for custom cases probably won't work out in a universally handleable manner. At least I can't think of a way how code could decide what can go away and what not. Implementing a set of manually crafted places is hard to maintain and prone to errors.

During development I played with displaying a file tree for obsolete files rather than a straight list. This quickly looked messy, because it made the list much longer, like 5 or 8 lines for a single file.

**Comment by yaniv14** [comment]
Than why don't just exclude autoupgrade folder completely from the obsolete scan?
or maybe show obsolete folders in a seperate line?
if its not something that you think is doable and/or valuable feel free to close this issue/topic.

**Comment by Traumflug** [comment]
Core Updater simply doesn't make such decisions. You have this particular case, another merchant has another folder, a third merchant complains about these files not being flagged as obsolete despite them being obsolete, a fourth merchant complains about them not being automatically removed, a fifth merchant complains his folder _autoupgrade_ being gone, despite his $1000 wedding gift was inside there.

As long as there is no idiot-proof way to do the right thing for everybody, Core Updater keeps its fingers off.
